### ISSUE TITLE
Project environment missing

### ISSUE THREAD

**Issue by ChenZhao44** [QuEraComputing/QRC-tutorials#1]
It would be ideal to include the `Project.toml` file to provide users with an automatic process to set up the required Julia environment.

**Comment by johnzl-777** [comment]
I think the same can be said for the Python side of things, it would be nice to have a requirements.txt. Working on it now! I can also probably create the Project.toml as well (:

**Comment by MilanKornjacaQ** [comment]
Agree, thanks! Added a Project.toml. Appreciate help with python requirements.
